version: '3'
services:
  nginx:
    image: kumaradji/nginx-server:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/static:/static
    depends_on:
      - web

  web:
    image: kumaradji/django-app:latest
    env_file:
      - ./.env
    volumes:
      - ./myproject:/app
    depends_on:
      - db

  db:
    image: kumaradji/postgres-db:latest
    env_file:
      - ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data